

# 단계 1: React 애플리케이션 빌드
FROM node:14 as build

WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

RUN npm run build

# 단계 2: Nginx를 사용하여 애플리케이션 서빙
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
# 기본적으로 Nginx는 포그라운드에서 실행되므로, 컨테이너는 계속 실행 상태를 유지합니다.

# Nginx 설정 파일 추가
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
